### ISSUE TITLE
UnhandledPromiseRejectionWarning while generating a Ext JS CE application

### ISSUE THREAD

**Issue by wemersonjanuario** [sencha/ext-gen#155]
Hello. I have the error while creating a new app using Ext JS CE (myget)

npm login --registry=https://sencha.myget.org/F/community/npm/ --scope=@sencha
npm install -g @sencha/ext-gen
ext-gen app -a

i [ext]: ext-gen: C:\laragon\www\treinamento/my-app created
i [ext]: ext-gen: package.json created for my-app
i [ext]: ext-gen: webpack.config.js created for my-app
i [ext]: ext-gen: npm install -s started for my-app
i [ext]: ext-gen: npm install -s completed for my-app
(node:69972) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\laragon\www\treinamento\my-app\node_modules\@sencha\ext\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at stepCreate (C:\Users\wemer\AppData\Roaming\npm\node_modules\@sencha\ext-gen\ext-gen.js:606:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:69972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ardabeyazoglu** [comment]
Any update on this? Still giving the same error with 6.7

**Comment by ardabeyazoglu** [comment]
I solved it by patching ext-gen script with an extra line of code. Here are the details: https://stackoverflow.com/questions/54724299/unhandledpromiserejectionwarning-error-cannot-find-module-using-ext-gen/56316813#56316813

**Comment by predrag-nikolic-kombinat-dev** [comment]
I got a similar error, when running  `ext-gen app -a -t moderndesktop -n ModernApp`

```
i [ext]: ext-gen: npm install -s completed for modern-app
node:internal/modules/cjs/loader:1140
  const err = new Error(message);
              ^

Error: Cannot find module '/home/predrag/Documents/sandbox/modern-app/node_modules/@sencha/ext/package.json'
Require stack:
- /home/predrag/.npm/_npx/44944b390b9e229a/node_modules/@sencha/ext-gen/ext-gen.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at stepCreate (/home/predrag/.npm/_npx/44944b390b9e229a/node_modules/@sencha/ext-gen/ext-gen.js:734:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/predrag/.npm/_npx/44944b390b9e229a/node_modules/@sencha/ext-gen/ext-gen.js'
  ]
}

Node.js v18.20.8
```

Resolved it by downgrading Node to version 12 and re-running the command `ext-gen app -a -t moderndesktop -n ModernApp`
